name: Backend CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup with Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle
        run: ./gradlew clean cicd-api:build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build Docker Image
        run: docker build -t $DOCKER_IMAGE_NAME:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKER_IMAGE_NAME:latest

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Docker Login to Docker Hub for Pull
        run: sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: sudo docker pull $DOCKER_IMAGE_NAME:latest

      - name: Docker Compose Deploy
        run: |
          sudo docker compose -f ${{ secrets.DOCKER_COMPOSE_FILE_PATH }} down || true
          sudo docker compose -f ${{ secrets.DOCKER_COMPOSE_FILE_PATH }} up -d

      - name: Docker image Prune
        run: sudo docker image prune -af